#!/bin/bash -e

_pkgname="zarafa-postfixadmin"
_pkgurl="https://alarm/zarafa-postfixadmin/setup.php"
_pkgconfig="/etc/webapps/zarafa-postfixadmin/config.local.php"
_databasename="zarafapostfixadmin"
_databaseuser="zarafapostfixadmin"


read -s -p "MySQL Root Password:" _mysqlpassword

if [[ -z ${_mysqlpassword} ]];
then
    echo "Continue without password"
    mysqlexec="mysql -uroot -s -N -e"
else
    mysqlexec="mysql -uroot -p${_mysqlpassword} -s -N -e"
fi

if [[ -z $($mysqlexec "show databases like '${_databasename}%';") ]];
then
    echo "### Mysql database not found."
    echo "Setting up..."
    
    echo "### ATTENTION: Please write down this passwords!"
    
    _password=$(< /dev/urandom tr -dc A-Za-z0-9 | head -c16)
    echo "### Setting mysql password for user ${_databaseuser} to" ${_password}
    
    if [[ -z $($mysqlexec "use mysql; select * from user where user ='${_databaseuser}';") ]];
    then
    	$mysqlexec "CREATE USER '${_databaseuser}'@'localhost' IDENTIFIED BY '${_password}';"
    else
	$mysqlexec "SET PASSWORD FOR '${_databaseuser}'@'localhost' = PASSWORD('${_password}');"
    fi
    
    $mysqlexec "CREATE DATABASE ${_databasename};"
    $mysqlexec "GRANT ALL PRIVILEGES ON ${_databasename} . * TO '${_databaseuser}'@'localhost';"

    _setup_password=$(< /dev/urandom tr -dc 0-9 | head -c16)$(< /dev/urandom tr -dc A-Za-z0-9 | head -c16)
    echo "### Setting ${_pkgname} setup password to" ${_setup_password}
    _setup_password_enc=$($(dirname $0)/setup-password ${_setup_password})
    

    sed -i -e "s/\(configured']\s*=\s*\)\(.*\)\(;$\)/\1true\3/" ${_pkgconfig}
    sed -i -e "s/\(database_type']\s*=\s*\)\(.*\)\(;$\)/\1'mysql'\3/" ${_pkgconfig}
    sed -i -e "s/\(database_host']\s*=\s*\)\(.*\)\(;$\)/\1'localhost:\/run\/mysqld\/mysqld.sock'\3/" ${_pkgconfig}
    sed -i -e "s/\(database_user']\s*=\s*\)\(.*\)\(;$\)/\1'${_databaseuser}'\3/" ${_pkgconfig}
    sed -i -e "s/\(database_password']\s*=\s*\)\(.*\)\(;$\)/\1'${_password}'\3/" ${_pkgconfig}
    sed -i -e "s/\(database_name']\s*=\s*\)\(.*\)\(;$\)/\1'${_databasename}'\3/" ${_pkgconfig}
    sed -i -e "s/\(setup_password']\s*=\s*\)\(.*\)\(;$\)/\1'${_setup_password_enc}'\3/" ${_pkgconfig}
    
    echo "### Almost done!"
    echo "### Please visit ${_pkgurl} and create a superadmin account."
fi
