#!/bin/bash

# See setup.php

_salt=$(date +%s)"*127.0.0.1*"$(shuf -i 0-60000 -n 1)
_salt=$(echo -n "${_salt}" | md5sum | cut -f1 -d' ')
_setup_password="${_salt}:"$(echo -n "${_salt}:$1" | sha1sum | cut -f1 -d' ')
echo -n ${_setup_password}